CREATE DATABASE WORDLE

CREATE TABLE PALABRAS(

PALWORDLE VARCHAR(1000)

)


SELECT * FROM PALABRAS

INSERT INTO PALABRAS(PALWORDLE)
VALUES ('VENAS'), ('VETAS'), ('VIGAS'), ('VINOS'), ('VOLAR'), ('VOTAN'), ('VOTAR'), ('VOTEN'), ('VOTOS'), ('ZORRO')

INSERT INTO PALABRAS(PALWORDLE) VALUES ('PERRO')